
[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#EF9F76"
index = 16

[[colors.indexed_colors]]
color = "#F2D5CF"
index = 17

[colors.bright]
black = "#626880"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#A5ADCE"
yellow = "#E5C890"

[colors.cursor]
cursor = "#F2D5CF"
text = "#303446"

[colors.dim]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[colors.hints.end]
background = "#A5ADCE"
foreground = "#303446"

[colors.hints.start]
background = "#E5C890"
foreground = "#303446"

[colors.normal]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[colors.primary]
background = "#303446"
bright_foreground = "#C6D0F5"
dim_foreground = "#C6D0F5"
foreground = "#C6D0F5"

[colors.search.focused_match]
background = "#A6D189"
foreground = "#303446"



[colors.search.matches]
background = "#A5ADCE"
foreground = "#303446"

[colors.selection]
background = "#F2D5CF"
text = "#303446"

[colors.vi_mode_cursor]
cursor = "#BABBF1"
text = "#303446"

[env]
TERM = "xterm-256color"

[font]
size = 21.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false



[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1.0
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
